#
# Server ID and UID can be configured automatically using /mcmetrics setup.
# More information: https://docs.mcmetrics.net/quickstart
#
server_id: ""
uid: ""

# Should the plugin send anonymous usage data to BStats? This helps us track plugin usage across servers.
# This option needs a restart to take effect.
enable-bstats: true

# Should the plugin send anonymous error reports to Sentry? This helps us track and fix plugin errors.
# This option needs a restart to take effect.
enable-sentry: false

# The prefix used to determine whether a player is on Bedrock using GeyserMC.
# Currently used for the "Bedrock/Java users" experiment condition.
bedrock-prefix: "*"

# Add any UUIDs or player usernames here to exclude them from session tracking and experiments.
exempt-players: [
  "00000000-0000-0000-0000-000000000000",
  "ExamplePlayerUserName"
]

# Automatically subtracts a percentage from payment amounts to account for Tebex & transaction fees.
# For example, setting this to 0.05 will subtract 5% from all payments.
# Set to 0.0 to disable.
payment-fee: 0.00

# Sends additional debug information to the console.
debug: false