#
# Server ID and UID can be configured automatically using /mcmetrics setup.
# More information: https://docs.mcmetrics.net/quickstart
#
server_id: ""
uid: ""

# Should the plugin send anonymous usage data to BStats? This helps us track plugin usage across servers.
# This option needs a restart to take effect.
enable-bstats: true

# Should the plugin send anonymous error reports to Sentry? This helps us track and fix plugin errors.
# This option needs a restart to take effect.
enable-sentry: false

# The prefix used to determine whether a player is on Bedrock using GeyserMC.
# Currently used for the "Bedrock/Java users" experiment condition.
bedrock-prefix: "*"