name: "MCMetrics"
version: '${project.version}'
main: me.kicksquare.mcmspigot.MCMSpigot
api-version: 1.17
commands:
  mcmetrics:
    aliases: [ mcm, metrics ]
    permission: mcmetrics.command
    bans:
      description: Access global bans data
      permission: mcmetrics.bans
    description: MCMetrics main command
  /mcmetrics:
    description: MCMetrics main command
    permission: mcmetrics.command
  mcmpayment:
    description: Internal command used to generate payment log [MCMetrics]
  mcmexperiment:
    description: Internal command used to trigger an ab test [MCMetrics]


softdepend: [ PlaceholderAPI, BuyCraftX, CraftingStore ]